import type { ThemeDefinition } from "../types.js";

/**
 * DeployLens — görsel deployment karşılaştırma aracı (browser-compare).
 * Mevcut uygulama stok shadcn "neutral" kullanıyor ve marka rengi YOK;
 * primary olarak projenin kendi demo fixture'larındaki marka mavisi
 * (#0B5CFF, gradyan ucu #6B2CFF) benimsendi — geliştirici aracı estetiği.
 * Nötr eksen (neutral/gri) mevcut uygulamayla birebir korunuyor.
 */
export const deploylens: ThemeDefinition = {
  name: "deploylens",
  label: "DeployLens",
  project: "browser-compare",
  colors: {
    light: {
      background: "#FFFFFF",
      foreground: "#0A0A0A",
      card: "#FFFFFF",
      cardForeground: "#0A0A0A",
      popover: "#FFFFFF",
      popoverForeground: "#0A0A0A",
      primary: "#0B5CFF",
      primaryForeground: "#FAFAFA",
      secondary: "#F5F5F5",
      secondaryForeground: "#171717",
      muted: "#F5F5F5",
      mutedForeground: "#737373",
      accent: "#EFF4FF",
      accentForeground: "#0B3AA5",
      destructive: "#EF4444",
      destructiveForeground: "#FAFAFA",
      success: "#16A34A",
      successForeground: "#FAFAFA",
      warning: "#D97706",
      warningForeground: "#FAFAFA",
      info: "#0284C7",
      infoForeground: "#FAFAFA",
      border: "#E5E5E5",
      input: "#E5E5E5",
      ring: "#0B5CFF",
      chart1: "#0B5CFF",
      chart2: "#6B2CFF",
      chart3: "#16A34A",
      chart4: "#F59E0B",
      chart5: "#EF4444",
      sidebar: "#FAFAFA",
      sidebarForeground: "#0A0A0A",
      sidebarPrimary: "#0B5CFF",
      sidebarPrimaryForeground: "#FAFAFA",
      sidebarAccent: "#F5F5F5",
      sidebarAccentForeground: "#171717",
      sidebarBorder: "#E5E5E5",
      sidebarRing: "#0B5CFF",
      gradientFrom: "#0B5CFF",
      gradientTo: "#6B2CFF",
    },
    dark: {
      background: "#0A0A0A",
      foreground: "#FAFAFA",
      card: "#141414",
      cardForeground: "#FAFAFA",
      popover: "#141414",
      popoverForeground: "#FAFAFA",
      primary: "#4C82FF",
      primaryForeground: "#0A1633",
      secondary: "#262626",
      secondaryForeground: "#FAFAFA",
      muted: "#262626",
      mutedForeground: "#A3A3A3",
      accent: "#12213F",
      accentForeground: "#9DBBFF",
      destructive: "#DC2626",
      destructiveForeground: "#FAFAFA",
      success: "#22C55E",
      successForeground: "#052E16",
      warning: "#F59E0B",
      warningForeground: "#451A03",
      info: "#38BDF8",
      infoForeground: "#082F49",
      border: "#262626",
      input: "#262626",
      ring: "#4C82FF",
      chart1: "#4C82FF",
      chart2: "#9D7BFF",
      chart3: "#22C55E",
      chart4: "#FBBF24",
      chart5: "#F87171",
      sidebar: "#111111",
      sidebarForeground: "#FAFAFA",
      sidebarPrimary: "#4C82FF",
      sidebarPrimaryForeground: "#0A1633",
      sidebarAccent: "#262626",
      sidebarAccentForeground: "#FAFAFA",
      sidebarBorder: "#262626",
      sidebarRing: "#4C82FF",
      gradientFrom: "#0B5CFF",
      gradientTo: "#6B2CFF",
    },
  },
  typography: {
    fontSans: "Inter, ui-sans-serif, system-ui, -apple-system, sans-serif",
    fontSerif: "ui-serif, Georgia, serif",
    fontMono: "'JetBrains Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
    fontDisplay: "Inter, ui-sans-serif, system-ui, -apple-system, sans-serif",
  },
  radius: { base: 8 },
};
