import type { ThemeDefinition } from "../types.js";

/**
 * Dolap — gardırop/kombin uygulaması (myDolapApp, web + mobil).
 * Kaynak: packages/ui-tokens/src/tokens.ts (shadcn violet-on-zinc, HSL→hex çevrildi).
 * Marka henüz kesinleşmedi (kod adı); violet kimliği mevcut uygulamadan korunuyor.
 */
export const dolap: ThemeDefinition = {
  name: "dolap",
  label: "Dolap",
  project: "myDolapApp",
  colors: {
    light: {
      background: "#FFFFFF",
      foreground: "#09090B",
      card: "#FFFFFF",
      cardForeground: "#09090B",
      popover: "#FFFFFF",
      popoverForeground: "#09090B",
      primary: "#7C3AED",
      primaryForeground: "#FAFAFA",
      secondary: "#F4F4F5",
      secondaryForeground: "#18181B",
      muted: "#F4F4F5",
      mutedForeground: "#71717A",
      accent: "#F4F4F5",
      accentForeground: "#18181B",
      destructive: "#EF4444",
      destructiveForeground: "#FAFAFA",
      success: "#16A34A",
      successForeground: "#FAFAFA",
      warning: "#D97706",
      warningForeground: "#FAFAFA",
      info: "#0284C7",
      infoForeground: "#FAFAFA",
      border: "#E4E4E7",
      input: "#E4E4E7",
      ring: "#7C3AED",
      chart1: "#7C3AED",
      chart2: "#A78BFA",
      chart3: "#EC4899",
      chart4: "#10B981",
      chart5: "#F59E0B",
      sidebar: "#FAFAFA",
      sidebarForeground: "#09090B",
      sidebarPrimary: "#7C3AED",
      sidebarPrimaryForeground: "#FAFAFA",
      sidebarAccent: "#F4F4F5",
      sidebarAccentForeground: "#18181B",
      sidebarBorder: "#E4E4E7",
      sidebarRing: "#7C3AED",
      gradientFrom: "#7C3AED",
      gradientTo: "#A855F7",
      shadowColor: "#4C1D95",
    },
    dark: {
      background: "#09090B",
      foreground: "#FAFAFA",
      card: "#09090B",
      cardForeground: "#FAFAFA",
      popover: "#09090B",
      popoverForeground: "#FAFAFA",
      primary: "#8B5CF6",
      primaryForeground: "#FAFAFA",
      secondary: "#27272A",
      secondaryForeground: "#FAFAFA",
      muted: "#27272A",
      mutedForeground: "#A1A1AA",
      accent: "#27272A",
      accentForeground: "#FAFAFA",
      destructive: "#B91C1C",
      destructiveForeground: "#FAFAFA",
      success: "#22C55E",
      successForeground: "#052E16",
      warning: "#F59E0B",
      warningForeground: "#451A03",
      info: "#38BDF8",
      infoForeground: "#082F49",
      border: "#27272A",
      input: "#27272A",
      ring: "#8B5CF6",
      chart1: "#8B5CF6",
      chart2: "#C4B5FD",
      chart3: "#F472B6",
      chart4: "#34D399",
      chart5: "#FBBF24",
      sidebar: "#111113",
      sidebarForeground: "#FAFAFA",
      sidebarPrimary: "#8B5CF6",
      sidebarPrimaryForeground: "#FAFAFA",
      sidebarAccent: "#27272A",
      sidebarAccentForeground: "#FAFAFA",
      sidebarBorder: "#27272A",
      sidebarRing: "#8B5CF6",
      gradientFrom: "#8B5CF6",
      gradientTo: "#C084FC",
      shadowColor: "#0B0212",
    },
  },
  typography: {
    fontSans: "Manrope, ui-sans-serif, system-ui, sans-serif",
    fontSerif: "Fraunces, ui-serif, Georgia, serif",
    fontMono: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontDisplay: "Fraunces, ui-serif, Georgia, serif",
  },
  radius: { base: 14 },
};
