import type { ThemeDefinition } from "../types.js";

/**
 * GlowScan — yüz/cilt analizi güzellik uygulaması (face-analizy-app).
 * Kaynak: src/theme/colors.ts (WCAG AA doğrulanmış değerler birebir alındı).
 * Estetik: zarif, feminen, premium spa — krem zemin, gül/leylak primary,
 * şeftali accent, serif tipografi (Cormorant Garamond + Playfair Display).
 */
export const glowscan: ThemeDefinition = {
  name: "glowscan",
  label: "GlowScan",
  project: "face-analizy-app",
  colors: {
    light: {
      background: "#FFF8F9",
      foreground: "#573746",
      card: "#FFFFFF",
      cardForeground: "#573746",
      popover: "#FFFFFF",
      popoverForeground: "#573746",
      primary: "#B34F82",
      primaryForeground: "#FFFFFF",
      secondary: "#FDE8F1",
      secondaryForeground: "#9A5577",
      muted: "#F9EFF1",
      mutedForeground: "#806575",
      accent: "#EEB4AA",
      accentForeground: "#573746",
      destructive: "#E7000B",
      destructiveForeground: "#FFFFFF",
      success: "#1F7A46",
      successForeground: "#FFFFFF",
      warning: "#8A5A00",
      warningForeground: "#FFFFFF",
      info: "#1F5B94",
      infoForeground: "#FFFFFF",
      border: "#EFE0E6",
      input: "#F3E8E9",
      ring: "#D06F9D",
      chart1: "#C66897",
      chart2: "#E69688",
      chart3: "#B484BF",
      chart4: "#CB8A8E",
      chart5: "#D9AD8A",
      sidebar: "#FDF1F5",
      sidebarForeground: "#573746",
      sidebarPrimary: "#B34F82",
      sidebarPrimaryForeground: "#FFFFFF",
      sidebarAccent: "#F9EFF1",
      sidebarAccentForeground: "#573746",
      sidebarBorder: "#EFE0E6",
      sidebarRing: "#CE6A99",
      gradientFrom: "#B34F82",
      gradientTo: "#C66897",
      shadowColor: "#4A2A33",
    },
    dark: {
      background: "#120506",
      foreground: "#F7F0EB",
      card: "#1F0E0F",
      cardForeground: "#F7F0EB",
      popover: "#1F0E0F",
      popoverForeground: "#F7F0EB",
      primary: "#E89DC0",
      primaryForeground: "#120506",
      secondary: "#38212C",
      secondaryForeground: "#F7F0EB",
      muted: "#2D2021",
      mutedForeground: "#B49DA7",
      accent: "#CD958B",
      accentForeground: "#120506",
      destructive: "#E81713",
      destructiveForeground: "#FFFFFF",
      success: "#7BD8A0",
      successForeground: "#16301F",
      warning: "#E5B764",
      warningForeground: "#3A2A10",
      info: "#88BDE8",
      infoForeground: "#152A3E",
      border: "#3B2F34",
      input: "#372A2B",
      ring: "#C987A6",
      chart1: "#E89DC0",
      chart2: "#E69688",
      chart3: "#C190CC",
      chart4: "#D8969B",
      chart5: "#E0B491",
      sidebar: "#1F0E0F",
      sidebarForeground: "#F7F0EB",
      sidebarPrimary: "#E89DC0",
      sidebarPrimaryForeground: "#120506",
      sidebarAccent: "#38212C",
      sidebarAccentForeground: "#F7F0EB",
      sidebarBorder: "#3B2F34",
      sidebarRing: "#C987A6",
      gradientFrom: "#E89DC0",
      gradientTo: "#C66897",
      shadowColor: "#000000",
    },
  },
  typography: {
    fontSans: "'Cormorant Garamond', ui-serif, Georgia, serif",
    fontSerif: "'Cormorant Garamond', ui-serif, Georgia, serif",
    fontMono: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontDisplay: "'Playfair Display', 'Cormorant Garamond', ui-serif, Georgia, serif",
  },
  radius: { base: 16 },
};
