import type { ThemeDefinition } from "../types.js";

/**
 * Randevu — randevu/rezervasyon platformu (appointment-global; web-public + web-admin).
 * Kaynak: apps/web-admin globals.css (indigo primary, zinc nötrler, Tailwind v4).
 * Randevu durum renkleri chart paletine yansıtıldı: indigo/mavi(onaylı)/
 * zümrüt(tamamlanan)/amber(bekleyen)/kırmızı(gelmedi).
 * Not: tenant bazlı runtime marka rengi override'ı proje tarafında korunur
 * (--primary/--ring/--secondary üzerine yazılır) — bu tema platform varsayılanıdır.
 */
export const randevu: ThemeDefinition = {
  name: "randevu",
  label: "Randevu",
  project: "appointment-global",
  colors: {
    light: {
      background: "#FFFFFF",
      foreground: "#0A0A0A",
      card: "#FFFFFF",
      cardForeground: "#0A0A0A",
      popover: "#FFFFFF",
      popoverForeground: "#0A0A0A",
      primary: "#4F46E5",
      primaryForeground: "#FAFAFA",
      secondary: "#F4F4F5",
      secondaryForeground: "#18181B",
      muted: "#F4F4F5",
      mutedForeground: "#71717A",
      accent: "#EEF2FF",
      accentForeground: "#3730A3",
      destructive: "#DC2626",
      destructiveForeground: "#FAFAFA",
      success: "#059669",
      successForeground: "#FAFAFA",
      warning: "#D97706",
      warningForeground: "#FAFAFA",
      info: "#2563EB",
      infoForeground: "#FAFAFA",
      border: "#E4E4E7",
      input: "#E4E4E7",
      ring: "#4F46E5",
      chart1: "#4F46E5",
      chart2: "#2563EB",
      chart3: "#059669",
      chart4: "#D97706",
      chart5: "#DC2626",
      sidebar: "#FAFAFA",
      sidebarForeground: "#0A0A0A",
      sidebarPrimary: "#4F46E5",
      sidebarPrimaryForeground: "#FAFAFA",
      sidebarAccent: "#F4F4F5",
      sidebarAccentForeground: "#18181B",
      sidebarBorder: "#E4E4E7",
      sidebarRing: "#4F46E5",
      gradientFrom: "#4F46E5",
      gradientTo: "#3B82F6",
    },
    dark: {
      background: "#0A0A0A",
      foreground: "#FAFAFA",
      card: "#18181B",
      cardForeground: "#FAFAFA",
      popover: "#18181B",
      popoverForeground: "#FAFAFA",
      primary: "#6366F1",
      primaryForeground: "#FAFAFA",
      secondary: "#27272A",
      secondaryForeground: "#FAFAFA",
      muted: "#27272A",
      mutedForeground: "#A1A1AA",
      accent: "#1E1B4B",
      accentForeground: "#C7D2FE",
      destructive: "#EF4444",
      destructiveForeground: "#FAFAFA",
      success: "#34D399",
      successForeground: "#022C22",
      warning: "#FBBF24",
      warningForeground: "#451A03",
      info: "#60A5FA",
      infoForeground: "#172554",
      border: "#27272A",
      input: "#27272A",
      ring: "#6366F1",
      chart1: "#818CF8",
      chart2: "#60A5FA",
      chart3: "#34D399",
      chart4: "#FBBF24",
      chart5: "#F87171",
      sidebar: "#111113",
      sidebarForeground: "#FAFAFA",
      sidebarPrimary: "#6366F1",
      sidebarPrimaryForeground: "#FAFAFA",
      sidebarAccent: "#27272A",
      sidebarAccentForeground: "#FAFAFA",
      sidebarBorder: "#27272A",
      sidebarRing: "#6366F1",
      gradientFrom: "#6366F1",
      gradientTo: "#60A5FA",
    },
  },
  typography: {
    fontSans: "ui-sans-serif, system-ui, -apple-system, sans-serif",
    fontSerif: "ui-serif, Georgia, serif",
    fontMono: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontDisplay: "ui-sans-serif, system-ui, -apple-system, sans-serif",
  },
  radius: { base: 10 },
};
